name: homechef
description: "DinnerHelp - Connect with professional chefs for unforgettable dining experiences at home."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  supabase_flutter: '>=1.10.0'
  flutter_svg: ^2.0.0
  geolocator: ^14.0.2
  permission_handler: ^11.0.0
  geocoding: ^3.0.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  awesome_bottom_bar: ^1.2.4
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  super_cupertino_navigation_bar: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true
