name: homechef
description: "DinnerHelp - Connect with professional chefs for unforgettable dining experiences at home."
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  supabase_flutter: '>=1.10.0'
  flutter_svg: ^2.0.0
  geolocator: ^14.0.2
  permission_handler: ^11.0.0
  geocoding: ^3.0.0
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  awesome_bottom_bar: ^1.2.4
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  super_cupertino_navigation_bar: ^1.0.1
  flutter_dotenv: ^5.1.0
  # Additional packages for booking availability system
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  equatable: ^2.0.5
  flutter_hooks: ^0.20.5
  go_router: ^14.1.4
  postgrest: ^2.1.0
  # Payment processing
  flutter_stripe: ^11.3.0
  url_launcher: ^6.2.2
  uuid: ^4.2.1
  # Notifications
  http: ^1.1.0
  timezone: ^0.9.2
  # For OneSignal integration
  onesignal_flutter: ^5.1.2
  # For swipe actions
  flutter_slidable: ^3.1.1
  # For image picking
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
