// Mocks generated by Mockito 5.4.6 from annotations
// in homechef/test/features/booking/domain/services/booking_availability_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:homechef/core/error/failures.dart' as _i5;
import 'package:homechef/features/booking/domain/entities/booking_request.dart'
    as _i7;
import 'package:homechef/features/booking/domain/entities/chef_availability.dart'
    as _i10;
import 'package:homechef/features/booking/domain/entities/chef_schedule_settings.dart'
    as _i12;
import 'package:homechef/features/booking/domain/entities/chef_time_off.dart'
    as _i11;
import 'package:homechef/features/booking/domain/entities/chef_working_hours.dart'
    as _i9;
import 'package:homechef/features/booking/domain/entities/time_slot.dart'
    as _i6;
import 'package:homechef/features/booking/domain/repositories/booking_availability_repository.dart'
    as _i3;
import 'package:homechef/features/booking/domain/repositories/chef_schedule_repository.dart'
    as _i8;
import 'package:homechef/features/booking/domain/services/chef_schedule_service.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookingAvailabilityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookingAvailabilityRepository extends _i1.Mock
    implements _i3.BookingAvailabilityRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TimeSlot>>>
      getAvailableTimeSlots({
    required String? chefId,
    required DateTime? date,
    required Duration? duration,
    required int? numberOfGuests,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAvailableTimeSlots,
              [],
              {
                #chefId: chefId,
                #date: date,
                #duration: duration,
                #numberOfGuests: numberOfGuests,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TimeSlot>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.TimeSlot>>(
              this,
              Invocation.method(
                #getAvailableTimeSlots,
                [],
                {
                  #chefId: chefId,
                  #date: date,
                  #duration: duration,
                  #numberOfGuests: numberOfGuests,
                },
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TimeSlot>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.TimeSlot>>(
              this,
              Invocation.method(
                #getAvailableTimeSlots,
                [],
                {
                  #chefId: chefId,
                  #date: date,
                  #duration: duration,
                  #numberOfGuests: numberOfGuests,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TimeSlot>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> checkBookingConflict({
    required String? chefId,
    required DateTime? date,
    required String? startTime,
    required String? endTime,
    String? excludeBookingId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkBookingConflict,
          [],
          {
            #chefId: chefId,
            #date: date,
            #startTime: startTime,
            #endTime: endTime,
            #excludeBookingId: excludeBookingId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #checkBookingConflict,
            [],
            {
              #chefId: chefId,
              #date: date,
              #startTime: startTime,
              #endTime: endTime,
              #excludeBookingId: excludeBookingId,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #checkBookingConflict,
            [],
            {
              #chefId: chefId,
              #date: date,
              #startTime: startTime,
              #endTime: endTime,
              #excludeBookingId: excludeBookingId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> validateBookingRequest(
          {required _i7.BookingRequest? bookingRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateBookingRequest,
          [],
          {#bookingRequest: bookingRequest},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #validateBookingRequest,
            [],
            {#bookingRequest: bookingRequest},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #validateBookingRequest,
            [],
            {#bookingRequest: bookingRequest},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TimeSlot>>>
      getChefScheduleForWeek({
    required String? chefId,
    required DateTime? weekStart,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getChefScheduleForWeek,
              [],
              {
                #chefId: chefId,
                #weekStart: weekStart,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TimeSlot>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.TimeSlot>>(
              this,
              Invocation.method(
                #getChefScheduleForWeek,
                [],
                {
                  #chefId: chefId,
                  #weekStart: weekStart,
                },
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TimeSlot>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.TimeSlot>>(
              this,
              Invocation.method(
                #getChefScheduleForWeek,
                [],
                {
                  #chefId: chefId,
                  #weekStart: weekStart,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TimeSlot>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.TimeSlot?>> getNextAvailableSlot({
    required String? chefId,
    required DateTime? afterDate,
    required Duration? duration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextAvailableSlot,
          [],
          {
            #chefId: chefId,
            #afterDate: afterDate,
            #duration: duration,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.TimeSlot?>>.value(
            _FakeEither_0<_i5.Failure, _i6.TimeSlot?>(
          this,
          Invocation.method(
            #getNextAvailableSlot,
            [],
            {
              #chefId: chefId,
              #afterDate: afterDate,
              #duration: duration,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.TimeSlot?>>.value(
                _FakeEither_0<_i5.Failure, _i6.TimeSlot?>(
          this,
          Invocation.method(
            #getNextAvailableSlot,
            [],
            {
              #chefId: chefId,
              #afterDate: afterDate,
              #duration: duration,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.TimeSlot?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isChefAvailable({
    required String? chefId,
    required DateTime? startTime,
    required DateTime? endTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isChefAvailable,
          [],
          {
            #chefId: chefId,
            #startTime: startTime,
            #endTime: endTime,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isChefAvailable,
            [],
            {
              #chefId: chefId,
              #startTime: startTime,
              #endTime: endTime,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isChefAvailable,
            [],
            {
              #chefId: chefId,
              #startTime: startTime,
              #endTime: endTime,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}

/// A class which mocks [ChefScheduleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChefScheduleRepository extends _i1.Mock
    implements _i8.ChefScheduleRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.ChefWorkingHours?>> getWorkingHours({
    required String? chefId,
    required int? dayOfWeek,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkingHours,
          [],
          {
            #chefId: chefId,
            #dayOfWeek: dayOfWeek,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i9.ChefWorkingHours?>>.value(
                _FakeEither_0<_i5.Failure, _i9.ChefWorkingHours?>(
          this,
          Invocation.method(
            #getWorkingHours,
            [],
            {
              #chefId: chefId,
              #dayOfWeek: dayOfWeek,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i9.ChefWorkingHours?>>.value(
                _FakeEither_0<_i5.Failure, _i9.ChefWorkingHours?>(
          this,
          Invocation.method(
            #getWorkingHours,
            [],
            {
              #chefId: chefId,
              #dayOfWeek: dayOfWeek,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i9.ChefWorkingHours?>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i9.ChefWorkingHours>>> getAllWorkingHours(
          {required String? chefId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllWorkingHours,
          [],
          {#chefId: chefId},
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i9.ChefWorkingHours>>>.value(
            _FakeEither_0<_i5.Failure, List<_i9.ChefWorkingHours>>(
          this,
          Invocation.method(
            #getAllWorkingHours,
            [],
            {#chefId: chefId},
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, List<_i9.ChefWorkingHours>>>.value(
            _FakeEither_0<_i5.Failure, List<_i9.ChefWorkingHours>>(
          this,
          Invocation.method(
            #getAllWorkingHours,
            [],
            {#chefId: chefId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i9.ChefWorkingHours>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure,
          List<_i10.ChefAvailability>>> getSpecificAvailability({
    required String? chefId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpecificAvailability,
          [],
          {
            #chefId: chefId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i10.ChefAvailability>>>.value(
            _FakeEither_0<_i5.Failure, List<_i10.ChefAvailability>>(
          this,
          Invocation.method(
            #getSpecificAvailability,
            [],
            {
              #chefId: chefId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, List<_i10.ChefAvailability>>>.value(
            _FakeEither_0<_i5.Failure, List<_i10.ChefAvailability>>(
          this,
          Invocation.method(
            #getSpecificAvailability,
            [],
            {
              #chefId: chefId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i10.ChefAvailability>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i11.ChefTimeOff>>> getTimeOffPeriods({
    required String? chefId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTimeOffPeriods,
          [],
          {
            #chefId: chefId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i11.ChefTimeOff>>>.value(
                _FakeEither_0<_i5.Failure, List<_i11.ChefTimeOff>>(
          this,
          Invocation.method(
            #getTimeOffPeriods,
            [],
            {
              #chefId: chefId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i11.ChefTimeOff>>>.value(
                _FakeEither_0<_i5.Failure, List<_i11.ChefTimeOff>>(
          this,
          Invocation.method(
            #getTimeOffPeriods,
            [],
            {
              #chefId: chefId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i11.ChefTimeOff>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i12.ChefScheduleSettings>> getScheduleSettings(
          {required String? chefId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScheduleSettings,
          [],
          {#chefId: chefId},
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i12.ChefScheduleSettings>>.value(
            _FakeEither_0<_i5.Failure, _i12.ChefScheduleSettings>(
          this,
          Invocation.method(
            #getScheduleSettings,
            [],
            {#chefId: chefId},
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, _i12.ChefScheduleSettings>>.value(
            _FakeEither_0<_i5.Failure, _i12.ChefScheduleSettings>(
          this,
          Invocation.method(
            #getScheduleSettings,
            [],
            {#chefId: chefId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i12.ChefScheduleSettings>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateWorkingHours({
    required String? chefId,
    required List<_i9.ChefWorkingHours>? workingHours,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkingHours,
          [],
          {
            #chefId: chefId,
            #workingHours: workingHours,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateWorkingHours,
            [],
            {
              #chefId: chefId,
              #workingHours: workingHours,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateWorkingHours,
            [],
            {
              #chefId: chefId,
              #workingHours: workingHours,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addTimeOff({
    required String? chefId,
    required _i11.ChefTimeOff? timeOff,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTimeOff,
          [],
          {
            #chefId: chefId,
            #timeOff: timeOff,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addTimeOff,
            [],
            {
              #chefId: chefId,
              #timeOff: timeOff,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addTimeOff,
            [],
            {
              #chefId: chefId,
              #timeOff: timeOff,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateScheduleSettings({
    required String? chefId,
    required _i12.ChefScheduleSettings? settings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateScheduleSettings,
          [],
          {
            #chefId: chefId,
            #settings: settings,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateScheduleSettings,
            [],
            {
              #chefId: chefId,
              #settings: settings,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateScheduleSettings,
            [],
            {
              #chefId: chefId,
              #settings: settings,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addSpecificAvailability({
    required String? chefId,
    required _i10.ChefAvailability? availability,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSpecificAvailability,
          [],
          {
            #chefId: chefId,
            #availability: availability,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addSpecificAvailability,
            [],
            {
              #chefId: chefId,
              #availability: availability,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addSpecificAvailability,
            [],
            {
              #chefId: chefId,
              #availability: availability,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeTimeOff({
    required String? chefId,
    required String? timeOffId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTimeOff,
          [],
          {
            #chefId: chefId,
            #timeOffId: timeOffId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeTimeOff,
            [],
            {
              #chefId: chefId,
              #timeOffId: timeOffId,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeTimeOff,
            [],
            {
              #chefId: chefId,
              #timeOffId: timeOffId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isWorkingDay({
    required String? chefId,
    required DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isWorkingDay,
          [],
          {
            #chefId: chefId,
            #date: date,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isWorkingDay,
            [],
            {
              #chefId: chefId,
              #date: date,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isWorkingDay,
            [],
            {
              #chefId: chefId,
              #date: date,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}

/// A class which mocks [ChefScheduleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChefScheduleService extends _i1.Mock
    implements _i13.ChefScheduleService {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.ChefWorkingHours?>> getWorkingHours(
    String? chefId,
    int? dayOfWeek,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkingHours,
          [
            chefId,
            dayOfWeek,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i9.ChefWorkingHours?>>.value(
                _FakeEither_0<_i5.Failure, _i9.ChefWorkingHours?>(
          this,
          Invocation.method(
            #getWorkingHours,
            [
              chefId,
              dayOfWeek,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i9.ChefWorkingHours?>>.value(
                _FakeEither_0<_i5.Failure, _i9.ChefWorkingHours?>(
          this,
          Invocation.method(
            #getWorkingHours,
            [
              chefId,
              dayOfWeek,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i9.ChefWorkingHours?>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i9.ChefWorkingHours>>> getAllWorkingHours(
          String? chefId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllWorkingHours,
          [chefId],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i9.ChefWorkingHours>>>.value(
            _FakeEither_0<_i5.Failure, List<_i9.ChefWorkingHours>>(
          this,
          Invocation.method(
            #getAllWorkingHours,
            [chefId],
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, List<_i9.ChefWorkingHours>>>.value(
            _FakeEither_0<_i5.Failure, List<_i9.ChefWorkingHours>>(
          this,
          Invocation.method(
            #getAllWorkingHours,
            [chefId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i9.ChefWorkingHours>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i11.ChefTimeOff>>> getTimeOffPeriods(
    String? chefId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTimeOffPeriods,
          [
            chefId,
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i11.ChefTimeOff>>>.value(
                _FakeEither_0<_i5.Failure, List<_i11.ChefTimeOff>>(
          this,
          Invocation.method(
            #getTimeOffPeriods,
            [
              chefId,
              startDate,
              endDate,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i11.ChefTimeOff>>>.value(
                _FakeEither_0<_i5.Failure, List<_i11.ChefTimeOff>>(
          this,
          Invocation.method(
            #getTimeOffPeriods,
            [
              chefId,
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i11.ChefTimeOff>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure,
          List<_i10.ChefAvailability>>> getSpecificAvailability(
    String? chefId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpecificAvailability,
          [
            chefId,
            date,
          ],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i10.ChefAvailability>>>.value(
            _FakeEither_0<_i5.Failure, List<_i10.ChefAvailability>>(
          this,
          Invocation.method(
            #getSpecificAvailability,
            [
              chefId,
              date,
            ],
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, List<_i10.ChefAvailability>>>.value(
            _FakeEither_0<_i5.Failure, List<_i10.ChefAvailability>>(
          this,
          Invocation.method(
            #getSpecificAvailability,
            [
              chefId,
              date,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i10.ChefAvailability>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Duration>> calculateBufferTime(
          String? chefId) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateBufferTime,
          [chefId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, Duration>>.value(
            _FakeEither_0<_i5.Failure, Duration>(
          this,
          Invocation.method(
            #calculateBufferTime,
            [chefId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, Duration>>.value(
                _FakeEither_0<_i5.Failure, Duration>(
          this,
          Invocation.method(
            #calculateBufferTime,
            [chefId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Duration>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getMaxBookingsPerDay(
          String? chefId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMaxBookingsPerDay,
          [chefId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getMaxBookingsPerDay,
            [chefId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, int>>.value(
                _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getMaxBookingsPerDay,
            [chefId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i12.ChefScheduleSettings>> getScheduleSettings(
          String? chefId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScheduleSettings,
          [chefId],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i12.ChefScheduleSettings>>.value(
            _FakeEither_0<_i5.Failure, _i12.ChefScheduleSettings>(
          this,
          Invocation.method(
            #getScheduleSettings,
            [chefId],
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, _i12.ChefScheduleSettings>>.value(
            _FakeEither_0<_i5.Failure, _i12.ChefScheduleSettings>(
          this,
          Invocation.method(
            #getScheduleSettings,
            [chefId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i12.ChefScheduleSettings>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isWorkingDay(
    String? chefId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isWorkingDay,
          [
            chefId,
            date,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isWorkingDay,
            [
              chefId,
              date,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isWorkingDay,
            [
              chefId,
              date,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TimeSlot>>>
      getEffectiveWorkingHours(
    String? chefId,
    DateTime? date,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getEffectiveWorkingHours,
              [
                chefId,
                date,
              ],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TimeSlot>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.TimeSlot>>(
              this,
              Invocation.method(
                #getEffectiveWorkingHours,
                [
                  chefId,
                  date,
                ],
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TimeSlot>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.TimeSlot>>(
              this,
              Invocation.method(
                #getEffectiveWorkingHours,
                [
                  chefId,
                  date,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TimeSlot>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateWorkingHours(
    String? chefId,
    List<_i9.ChefWorkingHours>? workingHours,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkingHours,
          [
            chefId,
            workingHours,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateWorkingHours,
            [
              chefId,
              workingHours,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateWorkingHours,
            [
              chefId,
              workingHours,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addTimeOff(
    String? chefId,
    _i11.ChefTimeOff? timeOff,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTimeOff,
          [
            chefId,
            timeOff,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addTimeOff,
            [
              chefId,
              timeOff,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addTimeOff,
            [
              chefId,
              timeOff,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateScheduleSettings(
    String? chefId,
    _i12.ChefScheduleSettings? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateScheduleSettings,
          [
            chefId,
            settings,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateScheduleSettings,
            [
              chefId,
              settings,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateScheduleSettings,
            [
              chefId,
              settings,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
